import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Header} from "../components/header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ COMBINE into one metadata object
export const metadata: Metadata = {
  title: "RealEstate Construction",
  description: "Generated by create next app",
  icons: {
    icon: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQj0Da0scT42MSuv0_MIEZTL4Hx2K-d05dwz5JgBKW-3rvhLS-rDWoWLiarhALUYv4ZSH4&usqp=CAU", // Make sure this file exists in /public folder
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          
         
        {children}
        <Header />
      </body>
    </html>
  );
}
